---

extends: default
rules:
  line-length: disable
  quoted-strings:
    quote-type: double
    required: "only-when-needed"
    extra-required:
      - "['\":{}\\[\\],&\\*#\\?|\\-<>=!%@]"
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
